/**
 * Chat Model
 * 
 * Represents a conversation thread. Each chat belongs to a user,
 * has a mode (determines the system prompt), and a title that
 * can be auto-generated by AI after the first message.
 */

const mongoose = require('mongoose');

const chatSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  title: {
    type: String,
    default: 'New Chat',
  },
  mode: {
    type: String,
    enum: ['general', 'coding', 'summarizer', 'eli5', 'study', 'writer'],
    default: 'general',
  },
  modelId: {
    type: String,
    default: 'llama-3.1-8b-instant',
  },
  customPrompt: {
    type: String,
    default: '',
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

// Auto-update updatedAt on save
chatSchema.pre('save', function (next) {
  this.updatedAt = new Date();
  next();
});

module.exports = mongoose.model('Chat', chatSchema);
